### PR TITLE
Fix two critical error

### PR DESCRIPTION
**Pull request by fuyutsuki**
### Description

Fixed some

### Reason to modify
- Think twice before modifying: is it the best way? will it break things? 
It is the best way.
- Have you made sure that there is actually a problem before trying to fix it?
Yes.
- Explain the logic behind your changes - WHY and HOW what you have done works
fixed syntax and FLAT generator`s error.
```php
$chunk->setBiomeColor()
```
is undefined.

### Tests & Reviews
It worked under the environment of Win10, php 7.0.15.
However, in this case, I think that the result will not change depending on the environment.

### CODE REVIEW

**Comment by caspervanneck** [comment]
@fuyutsuki  thnx I wash sleeping

**Comment by caspervanneck** [comment]
@fuyutsuki I going to invite you if you wanth

**Comment by fuyutsuki** [comment]
@caspervanneck Although I may not be useful much, I would appreciate your favor(and I'm Japanese… :P ).

**Comment by fuyutsuki** [comment]
@caspervanneck May I come in?

**Comment by caspervanneck** [comment]
Yes

**Comment by fuyutsuki** [comment]
@caspervanneck Entered, thank you.

**Pull request merged**
